### ISSUE TITLE
Website typo

### ISSUE THREAD

**Issue by rubenv** [FoundrySH/zipcodes#8]
```
Not all zip codes are available and the location may be inaccuarte or out-dated.
                                                        ^^^^^^^^^^
```

**Comment by rubenv** [comment]
I'd submit a pull request to fix it, but I can't seem to find a git repo for the website.

Awesome project by the way!

**Comment by FoundrySH** [comment]
The project has been moved to a more sustainable platform here: https://zipcodes.foundry.sh/
This fixed the typo issue.
